arch:
  - arm64
language: node_js
node_js:
  - 'stable'
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install: npm install
jobs:
  include:
    - stage: run tests
      script:
      - npm test
    - stage: build docker image
      script:
      - docker build -t animea-animes .
      - docker tag animea-animes animea/animea-animes:latest
      - docker push animea/animea-animes:latest
after_success: npm run coverage